version: '3.5'

services:

  db:
    image: postgres
    restart: always
    environment:
      PASSWORD_DB: ${POSTGRES_PASSWORD}

    container_name: postgrescontainer1
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    networks:
      - nest-postgresql-docker-compose-example1-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestcontainer1
    environment:
      POSTGRES_HOST: db
      PORT_DB: ${POSTGRES_PORT}
      PASSWORD_DB: ${POSTGRES_PASSWORD}
      APP_PORT: 9876
    ports:
      - '9876:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - nest-postgresql-docker-compose-example1-network

networks:
  nest-postgresql-docker-compose-example1-network:
    driver: bridge

  # Для запуска используем команду в терминале вебшторма
  #docker-compose up


  #в браузере   http://localhost:9876 и получу данные из базы
  #http://localhost:9876/new    и создам один обьект
  # больше приложение ничего неумеет
  # РАБОТАЕТ ВНУТРИ КОНТЕЙНЕРА